syntax on
filetype plugin indent on

set number
set showmatch

set tabstop=4
set shiftwidth=4
set expandtab
set cindent

set laststatus=2
set statusline=%f\ %y\ %m\ %=%l:%c

set hlsearch
set incsearch

set cursorline
set cursorlineopt=number
highlight LineNr ctermfg=Grey
highlight CursorLineNr cterm=bold ctermfg=Blue
